const englishQuizQuestions = [
  {
    id: 1,
    question: "What is the synonym of 'happy'?",
    options: ["Joyful", "Sad", "Excited", "Angry"],
    correctOption: "Joyful",
  },
  {
    id: 2,
    question: "Choose the correct spelling:",
    options: ["Accomodate", "Accommodate", "Acommodate", "Acomodate"],
    correctOption: "Accommodate",
  },
  /*{
    id: 3,
    question: "What is the opposite of 'victory'?",
    options: ["Defeat", "Triumph", "Success", "Win"],
    correctOption: "Defeat",
  },
  {
    id: 4,
    question: "Select the correct plural form of 'child':",
    options: ["Childs", "Childrens", "Childes", "Children"],
    correctOption: "Children",
  },
  {
    id: 5,
    question: "Which word is a verb?",
    options: ["Running", "Fast", "Quick", "Speed"],
    correctOption: "Running",
  },
  {
    id: 6,
    question: "Identify the antonym of 'beautiful':",
    options: ["Ugly", "Pretty", "Attractive", "Gorgeous"],
    correctOption: "Ugly",
  },
  {
    id: 7,
    question: "Choose the correct preposition:",
    options: ["In", "On", "At", "For"],
    correctOption: "On",
  },
  {
    id: 8,
    question: "What is the plural of 'mouse'?",
    options: ["Mouses", "Mice", "Mousies", "Mouse"],
    correctOption: "Mice",
  },
  {
    id: 9,
    question: "Which sentence is grammatically correct?",
    options: [
      "She don't like pizza.",
      "She doesn't like pizza.",
      "She not likes pizza.",
      "She not liking pizza.",
    ],
    correctOption: "She doesn't like pizza.",
  },
  {
    id: 10,
    question: "What is the meaning of 'benevolent'?",
    options: ["Cruel", "Kind", "Generous", "Greedy"],
    correctOption: "Generous",
  },
  {
    id: 11,
    question: "Choose the correctly punctuated sentence:",
    options: [
      "The cat sat on the mat",
      "The cat, sat on the mat.",
      "The cat sat, on the mat.",
      "The cat sat on the mat.",
    ],
    correctOption: "The cat sat on the mat.",
  },
  {
    id: 12,
    question: "Which is the correct spelling?",
    options: ["Recieve", "Receive", "Receieve", "Receve"],
    correctOption: "Receive",
  },
  {
    id: 13,
    question: "What is the synonym of 'brave'?",
    options: ["Cowardly", "Fearful", "Courageous", "Timid"],
    correctOption: "Courageous",
  },
  {
    id: 14,
    question: "Choose the correct conjunction:",
    options: ["And", "But", "Or", "So"],
    correctOption: "And",
  },
  {
    id: 15,
    question: "Identify the correct article:",
    options: ["A", "An", "The", "None"],
    correctOption: "An",
  },
  {
    id: 16,
    question: "What is the plural of 'goose'?",
    options: ["Gooses", "Geese", "Goosies", "Goose"],
    correctOption: "Geese",
  },
  {
    id: 17,
    question: "Which is the correctly spelled color?",
    options: ["Gray", "Grey", "Grae", "Greay"],
    correctOption: "Gray",
  },
  {
    id: 18,
    question: "What is the opposite of 'generous'?",
    options: ["Greedy", "Stingy", "Kind", "Altruistic"],
    correctOption: "Stingy",
  },
  {
    id: 19,
    question: "Choose the correct form of 'to be' in the past tense:",
    options: ["Am", "Is", "Was", "Are"],
    correctOption: "Was",
  },
  {
    id: 20,
    question: "Identify the correct homophone:",
    options: ["Flour", "Flower", "Hour", "Our"],
    correctOption: "Flower",
  },
  {
    id: 21,
    question: "What is the meaning of 'ephemeral'?",
    options: ["Lasting a very short time", "Permanent", "Eternal", "Endless"],
    correctOption: "Lasting a very short time",
  },
  {
    id: 22,
    question: "Choose the correct modal verb:",
    options: ["Can", "Do", "Have", "Will"],
    correctOption: "Can",
  },
  {
    id: 23,
    question: "Which is the correct possessive form?",
    options: ["Cat's", "Cats'", "Cats's", "Cats"],
    correctOption: "Cat's",
  },
  {
    id: 24,
    question: "What is the synonym of 'cozy'?",
    options: ["Uncomfortable", "Warm", "Spacious", "Cold"],
    correctOption: "Warm",
  },
  {
    id: 25,
    question: "Choose the correct demonstrative pronoun:",
    options: ["He", "She", "This", "It"],
    correctOption: "This",
  },
  {
    id: 26,
    question: "What is the plural of 'knife'?",
    options: ["Knifes", "Knives", "Knife's", "Knive"],
    correctOption: "Knives",
  },
  {
    id: 27,
    question: "Identify the correct phrasal verb:",
    options: ["Look after", "Look in", "Look on", "Look up"],
    correctOption: "Look after",
  },
  {
    id: 28,
    question: "Choose the correct comparative form:",
    options: ["Good", "Better", "Best", "Goodest"],
    correctOption: "Better",
  },
  {
    id: 29,
    question: "What is the meaning of 'meticulous'?",
    options: ["Careless", "Sloppy", "Thorough", "Untidy"],
    correctOption: "Thorough",
  },
  {
    id: 30,
    question: "Select the correct past participle:",
    options: ["Run", "Ran", "Running", "Runned"],
    correctOption: "Run",
  },
  {
    id: 31,
    question: "What is the opposite of 'courage'?",
    options: ["Bravery", "Fear", "Strength", "Daring"],
    correctOption: "Fear",
  },
  {
    id: 32,
    question: "Choose the correct conjunction:",
    options: ["Although", "Therefore", "However", "Furthermore"],
    correctOption: "Although",
  },
  {
    id: 33,
    question: "Identify the correct modal verb:",
    options: ["May", "Have", "Do", "Is"],
    correctOption: "May",
  },
  {
    id: 34,
    question: "What is the plural of 'foot'?",
    options: ["Feets", "Foots", "Feet", "Footies"],
    correctOption: "Feet",
  },
  {
    id: 35,
    question: "Choose the correct preposition:",
    options: ["Between", "Beside", "Among", "Across"],
    correctOption: "Between",
  },
  {
    id: 36,
    question: "What is the synonym of 'confident'?",
    options: ["Timid", "Shy", "Assured", "Fearful"],
    correctOption: "Assured",
  },
  {
    id: 37,
    question: "Which is the correctly spelled fruit?",
    options: ["Bananna", "Banana", "Bananah", "Banan"],
    correctOption: "Banana",
  },
  {
    id: 38,
    question: "What is the opposite of 'ancient'?",
    options: ["Old", "Antique", "Modern", "Timeless"],
    correctOption: "Modern",
  },
  {
    id: 39,
    question: "Select the correct comparative form:",
    options: ["Larger", "Large", "Largely", "Largen"],
    correctOption: "Larger",
  },
  {
    id: 40,
    question: "Identify the correct homograph:",
    options: ["Tear", "Tear", "Tier", "Tire"],
    correctOption: "Tear",
  },
  {
    id: 41,
    question: "What is the meaning of 'ephemeral'?",
    options: ["Lasting a very short time", "Permanent", "Eternal", "Endless"],
    correctOption: "Lasting a very short time",
  },
  {
    id: 42,
    question: "Choose the correct modal verb:",
    options: ["Can", "Do", "Have", "Will"],
    correctOption: "Can",
  },
  {
    id: 43,
    question: "Which is the correct possessive form?",
    options: ["Cat's", "Cats'", "Cats's", "Cats"],
    correctOption: "Cat's",
  },
  {
    id: 44,
    question: "What is the synonym of 'cozy'?",
    options: ["Uncomfortable", "Warm", "Spacious", "Cold"],
    correctOption: "Warm",
  },
  {
    id: 45,
    question: "Choose the correct demonstrative pronoun:",
    options: ["He", "She", "This", "It"],
    correctOption: "This",
  },
  {
    id: 46,
    question: "What is the plural of 'knife'?",
    options: ["Knifes", "Knives", "Knife's", "Knive"],
    correctOption: "Knives",
  },
  {
    id: 47,
    question: "Identify the correct phrasal verb:",
    options: ["Look after", "Look in", "Look on", "Look up"],
    correctOption: "Look after",
  },
  {
    id: 48,
    question: "Choose the correct comparative form:",
    options: ["Good", "Better", "Best", "Goodest"],
    correctOption: "Better",
  },
  {
    id: 49,
    question: "What is the meaning of 'meticulous'?",
    options: ["Careless", "Sloppy", "Thorough", "Untidy"],
    correctOption: "Thorough",
  },
  {
    id: 50,
    question: "What does the acronym 'NASA' stand for?",
    options: [
      "National Aeronautics and Space Association",
      "National Aviation and Space Administration",
      "North American Space Agency",
      "None of the above",
    ],
    correctOption: "National Aeronautics and Space Administration",
  },*/
];
export default englishQuizQuestions;